source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JSSAlertView_Example', :exclusive => true do
  pod 'JSSAlertView', :path => '../'
end

target 'JSSAlertView_Tests', :exclusive => true do
  pod 'JSSAlertView', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
