name: Release

on:
  push:
    branches:
      - refs/tags/*

jobs:
  build:

    runs-on: macOS-latest

    - name: Lint Podspec
      run: pod lib lint JSSAlertView.podspec
    - name: Push Trunk
      run: pod trunk push JSSAlertView.podspec
